name: "Build main"

on:
  push:
    branches:
      - main

env:
  JAVA_OPTS: -Xms512m -Xmx1024m
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.configureondemand=true -Dorg.gradle.jvmargs=-Xmx3g -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"

jobs:
  build:
    env:
      JAVA_OPTS: -Xms512m -Xmx1024m

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        run: ./gradlew build --scan
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Dokka
        id: Dokka
        continue-on-error: true
        run: |
          ./gradlew dokkaGfm --scan
          exit $((git status --porcelain | wc -c)

      - name: Commit Changes
        if: steps.Dokka.outcome == 'failure'
        run: |
          git config --global user.name 'AutoDocAction'
          git config --global user.email 'AudoDocAction@no-reply.com'
          git add /docs
          git commit -m "automatically update documentation"
          git push
